### ISSUE TITLE
[BUG] Not loading

### ISSUE THREAD

**Issue by serhatkilicv** [jonjomckay/fritter#324]
**Device**
Redmi Note 9 PRO Turkish

![Screenshot_2022-01-23-18-10-57-441_com jonjomckay fritter](https://user-images.githubusercontent.com/98114446/150685134-9bb125f9-7f7f-486c-b987-0744a1b544c0.jpg)

**Comment by johnr-de** [comment]
Same here. v2.16.2+20220120
General Feed fine but as soon as you try to load individual feeds, error occurs.
Samsung A9 / localisation German

"
![Uploading Screenshot_20220123-183144_Fritter.jpg…]()

**Comment by swinkapepa** [comment]
Problem solved with v2.16.3+20220123, thank you @jonjomckay

**Comment by wachfo** [comment]
The same bug on my Samsung A51 since last update

**Comment by poubellier** [comment]
> Problem solved with v2.16.3+20220123, thank you @jonjomckay


![Screenshot_20220123-195323](https://user-images.githubusercontent.com/98282479/150794192-49db9183-c1cd-4666-beea-189838ef7e62.png)
Unable to install v2.16.3+20220123. So still having the bug. Latest calyx os beta, pixel 6

**Comment by cristobalcampr** [comment]
Same here using the latest release. Realme GT.

**Comment by swinkapepa** [comment]
> > Problem solved with v2.16.3+20220123, thank you @jonjomckay
> 
> ![Screenshot_20220123-195323](https://user-images.githubusercontent.com/98282479/150794192-49db9183-c1cd-4666-beea-189838ef7e62.png) Unable to install v2.16.3+20220123. So still having the bug. Latest calyx os beta, pixel 6

I use calyx but stable on p4a and there is no problem at all.

**Comment by wongfeihung1984** [comment]
@swinkapepa I can't install the latest version either (I couldn't install the one before that one, too) : a message pops up and write "Application not installed"

**Comment by jonjomckay** [comment]
This should be fixed in v2.16.3 now.

One thing to note - if you have the F-Droid version installed, and you try and upgrade using an APK from GitHub, it won't work. Android doesn't let you upgrade apps signed with different keys (F-Droid uses their own key). You should be able to get around this by exporting your data from Fritter, uninstalling the F-Droid version, installing the GitHub version, then re-importing your data. Otherwise, v2.16.3 should be making its way to F-Droid in the next few days!
