### ISSUE TITLE
[BUG] Settings page: Wrong navigation behavior

### ISSUE THREAD

**Issue by nannadroid** [jonjomckay/fritter#523]
**Describe the bug**
Tabs do not switch correctly when navigating through them in Settings page. Have to keep on clicking the destination tab until it opens.

**To Reproduce**
1. Go to 'Settings'
2. Click on different tabs at the bottom
3. See error

**Screenshots**
https://user-images.githubusercontent.com/113890947/192091671-6e1be398-6786-4bbb-a919-3860d50b6c58.mp4

**Device**
Fritter: beta 3.0.0
Android 11, OxygenOS 11.1.2.2
OnePlus 6

**Comment by Aga-C** [comment]
It's already fixed in the latest version (v3.0.0-beta4).

**Comment by nannadroid** [comment]
> It's already fixed in the latest version (v3.0.0-beta4).

When will this be available in playstore for update?

**Comment by johann-gambol** [comment]
The bug is still in the current version [04e7a85c5285ebc3820c9715fc3f0c4bfe95543b] though. I guess it's the same issue as #471. I already made a pull request to fix it.

**Comment by nannadroid** [comment]
Thank you!

**Comment by jonjomckay** [comment]
It will be available in the Play Store's beta programme as soon as it passes the review - I'm not sure when that will be though.

Closing this for now, as it is fixed.

**Comment by nannadroid** [comment]
> It will be available in the Play Store's beta programme as soon as it passes the review - I'm not sure when that will be though.
> 
> Closing this for now, as it is fixed.

Is this beta version available now?
