### ISSUE TITLE
[BUG]Searching for text results in "Catastropic Failure" message

### ISSUE THREAD

**Issue by RenBuddy** [jonjomckay/fritter#577]
> Please make sure you've tried the [latest version](https://github.com/jonjomckay/fritter/releases) of Fritter first, as the F-Droid version is sometimes out of date!

**Describe the bug**
A clear description of what the bug is.
When I try to do a search (by clicking on the Search icon and typing in text) I get the message Catastrophic Failure/Missing or invalid url parameter. This only happens if I click on the Replies icon; searches still work if I click on the Accounts icon.
*Edited to add: I uninstalled the 2.16.3 version and installed v3.0.0-beta5+20221126 version and the problem persists.

**To Reproduce**
1. Go to Search icon (magnifying glass)
2. Type in any text. Click on Replies icon (message bubble icon)
3. Get message "Catastrophic Failure/Missing or invalid url parameter"

**Screenshots**

**Device**
Samsung Galaxy Note 9
OS version 10
En_US
English
2.16.3. AND v3.0.0-beta5+20221126

**Comment by jaum20** [comment]
Same here

**Comment by RenBuddy** [comment]
Update: Now clicking on anything in the Trending lists results in same "Catastrophic Failure" message.

**Comment by Rmn382** [comment]
same here!

the exact error message is: 

"Catastrophic failure
Missing vor invalid url parameter."

seems like twitter changed some URL Parameter requirements

**Comment by oldhubEr** [comment]
Same here too

**Comment by ahmeds189** [comment]
Nothing yet?

**Comment by jonjomckay** [comment]
This should be fixed now. Sorry for the delay - I haven't been able to spend as much time as I'd like on Fritter recently 🙁

**Comment by geominorai** [comment]
> This should be fixed now. Sorry for the delay - I haven't been able to spend as much time as I'd like on Fritter recently 🙁 

Thanks buddy. We really appreciate your work on this app even if it takes some time to update. ❤️

**Comment by RenBuddy** [comment]
I'm still getting the same errors. ? Any advice, when you get a chance. Thanks!

**Comment by geominorai** [comment]
The patch works for me on the new CI build.

**Comment by cellfdroid** [comment]
Not sure if something else need to happen for fdroid to pickup fix or if its something in my settings. Not seeing new builds after beta5
